version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web/static
      - media-data:/vol/web/media


  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - "80:5000"  
    volumes:
      - static-data:/vol/web/static  # Corrected volume path for static files
      - media-data:/vol/web/media   # Corrected volume path for media files

volumes:
  postgres-data:
  static-data:
  media-data:
